apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: meiga-{{.Release.Name}}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress_path }}
        backend:
          serviceName: web-{{ .Release.Name }}
          servicePort: 5000

